### PR TITLE
ci(travis): run commitlint on travis ci

### PR DESCRIPTION
**Pull request by ChristianMurphy**
removes `precommit` hook that verifies commit message locally.
Combined with #580 this removes all error level commit hooks.

Most recent local commit can still be checked with `npm run lint-commit`.

Travis CI now checks all commits in a feature branch to ensure they meet the formatting guidelines.

:notebook: I still see this as a step backward, checking if a commit message meets the conventional commit standard locally is a lot easier than rewriting history later.

part 2 of #535
part 1 is in #580

----

Contributor License Agreement adherence:

- [x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].

[Apereo CLA roster]: http://licensing.apereo.org/completed-clas
[Contributor License Agreements]: https://www.apereo.org/licensing/agreements

### CODE REVIEW

**Review by apetro — APPROVED** [review]

**Comment by vertein** [comment]
It appears that this has a merge conflict now.  Can you update @ChristianMurphy?

Thanks

**Comment by ChristianMurphy** [comment]
Absolutely!
Before that it would be nice to get sign off from @davidmsibley, since this PR was made based off his request.

**Review by davidmsibley — APPROVED** [review]
fantastic

**Comment by ChristianMurphy** [comment]
@vertein resynced with `master` branch and conflicts resolved

**Comment by ChristianMurphy** [comment]
:thinking: it looks like the shell script is having issues with the commit ranges in merge commits 
https://travis-ci.org/uPortal-Project/uportal-app-framework/jobs/289541275#L831-L846
It looks like it may be designed to be used with `git rebase` or `git pull --rebase`.

/cc @marionebl

**Comment by marionebl** [comment]
@ChristianMurphy  I am not entirely sure which `commitlint` call is tripping up here. 

* The logs contain some successful read/lint operations: [820](https://travis-ci.org/uPortal-Project/uportal-app-framework/jobs/289541275#L820) - [829](https://travis-ci.org/uPortal-Project/uportal-app-framework/jobs/289541275#L829)
* Then `commitlint` it is fed with `--from=c8571a40341b41123d473af172cc269d381b4cdf`, which appears to be invalid according to `git-raw-commits` 

Could you add some debug output
* before each `commitlint` call, stating if it is the "triggering commit" or "range" linting
* the exact `$FROM` and `$TO` values used

**Comment by ChristianMurphy** [comment]
welp, after I rebased it works, will add tracing in when/if it breaks again.

**Pull request merged**
