### PR TITLE
style(js,json,less): use 'prettier' to handle code style

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Rather than throwing an error during `precommit` hook.
`prettier` will reformat all the code to meet the styleguide standards automatically.

Check out this talk for more information on the 'why' to use prettier.
<a href="https://www.youtube.com/watch?v=hkfBvpEfWdA"></a>

part 1 of #535
part 2 is in https://github.com/uPortal-Project/uportal-app-framework/pull/581

----

Contributor License Agreement adherence:

- [x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].

[Apereo CLA roster]: http://licensing.apereo.org/completed-clas
[Contributor License Agreements]: https://www.apereo.org/licensing/agreements

### CODE REVIEW

**Review by apetro — APPROVED** [review]

**Review by davidmsibley — CHANGES_REQUESTED** [review]
This looks like it's replacing single quotes to double quotes, breaking the google style guide?

**Comment by ChristianMurphy** [comment]
@davidmsibley Currently I have `prettier` setup to use all of its defaults.
Those defaults are very similar, but subtly different than the Google Code style, we can adjust the settings to use single quotes.

**Comment by ChristianMurphy** [comment]
@davidmsibley updated to use single quotes

**Comment by davidmsibley** [comment]
I'm confused about a couple things in this. I gotta read it more, but I was referring to the single to double quote replacement that was happening in the js, not the less. Now the less is switched from double to single quotes.

Unrelated to whether or not we use prettier, I'm WAY more opposed to code _being changed_ on commit than stopping you from committing. That sounds like many, many unintended problems waiting to happen.

**Comment by ChristianMurphy** [comment]
:laughing: The codeclimate failure is occurring because the normalized code style allows codeclimate to detect nine places with code similarity that it wasn't able to before.

**Comment by vertein** [comment]
Does this automatically re-format to use Google's code style or does this use a separate style that we would have to match to Google's?

**Comment by apetro** [comment]
> subtly different than the Google Code style

Okay, I hadn't understood that nuance. -1.  Code is either in Google Style or it's not. Automatically different, even subtly, is not Google Style. I'd only be open to automatic code styling if it's automatically styling to the adopted code style. :)

This also may be a tool that it'd be best to adopt on a less-core module or three before adopting it here in `uportal-application-framework`. I'm not sure I share @davidmsibley 's prediction of many unintended problems, but I certainly see how a reasonable person would fear that. I think we can be way more open to experimental friction and risk in modules that we're less likely to need to release frequently *for adoption by other teams*, which is what this module is.

**Comment by ChristianMurphy** [comment]
> Code is either in Google Style or it's not. Automatically different, even subtly, is not Google Style.

> Does this automatically re-format to use Google's code style or does this use a separate style that we would have to match to Google's?

The subtle differences are trailing commas and quotes.
Both can be configured to match Google Code Style. :white_check_mark: 

> I'd only be open to automatic code styling if it's automatically styling to the adopted code style.

Or we could make the automated style the adopted style. :wink: 

> That sounds like many, many unintended problems waiting to happen.

I understand the concern, in the past formatters could be flaky. :fearful: 

Prettier and ESLint are based of [ESTree](https://github.com/estree/estree) an [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) standard [developed by Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API) for accurately representing and safely manipulating code structure. :+1: 
Using AST for code manipulation resolves the invalid parsing and serialization errors common in regular expression based parsers (which did have major issues with producing invalid code). :white_check_mark: 

Furthermore, Prettier is in production use today on some major projects: [React](https://github.com/facebook/react/blob/101934646f79660430a5e76487d6e5350e68a7eb/package.json#L103), [Jest](https://github.com/facebook/jest/blob/027622436da65957e8f2ff31ac2e222855a00421/package.json#L58), [Yarn](https://github.com/yarnpkg/yarn/blob/b97c797983babd03c68bc36f1ee98a9a6dff9246/package.json#L88), [and others](https://prettier.io/en/users/).
The software is pretty well battle tested. :crossed_swords: 

> This also may be a tool that it'd be best to adopt on a less-core module or three before adopting it here in `uportal-application-framework`

:man_shrugging: With the clean breakup of modules, it is arguably questionable if there is a "core" and what isn't core. Until recently I thought [`uPortal-home` was "core"](https://github.com/uPortal-Project/uportal-home/pull/704#discussion_r141414623).

> I think we can be way more open to experimental friction and risk in modules that we're less likely to need to release frequently for adoption by other teams, which is what this module is.

Since all the modules are closely interrelated, what is module is sufficiently "low risk" in your mind?

**Comment by apetro** [comment]
+ `uPortal-home` is lower risk than `uPortal-app-framework`, in that only the latter has downstream projects depending upon it.
+ [`widget-creator`](https://github.com/UW-Madison-DoIT/widget-creator) is much lower risk, in that its audience is developers.

**Comment by ChristianMurphy** [comment]
Closing this, til decision is made over in https://github.com/UW-Madison-DoIT/widget-creator/pull/25

**Pull request closed without merging**
