### PR TITLE
ci(travis): leverage commitlint travis helper

### PR DESCRIPTION
**Pull request by ChristianMurphy**
removes need for custom shell script to check commit messages.
moves `greenkeeper-lockfile` package into dev dependencies so updates can be tracked.

----

Contributor License Agreement adherence:

- [x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].

[Apereo CLA roster]: http://licensing.apereo.org/completed-clas
[Contributor License Agreements]: https://www.apereo.org/licensing/agreements

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
CI error is originating from https://github.com/marionebl/commitlint/pull/157
Upstream resolution coming soon.

**Comment by marionebl** [comment]
Chiming in here - the travis helper isn't quite ready for prime time yet. I am working out the kinks, tracking progress here: https://github.com/marionebl/commitlint/issues/99, testing reports welcome!

**Comment by ChristianMurphy** [comment]
the travis helper now is a officially recommended method https://github.com/marionebl/commitlint/pull/215
Updating this PR to get it merge-able.

**Comment by ChristianMurphy** [comment]
AppVeyor failing on unrelated issue

```
[INFO] --- exec-maven-plugin:1.3.2:exec (npm install (initialize)) @ uportal-app-framework ---
npm ERR! path C:\projects\uportal-app-framework\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\projects\uportal-app-framework\node_modules\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\projects\uportal-app-framework\node_modules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\projects\\uportal-app-framework\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\projects\\uportal-app-framework\\node_modules\\fsevents\\node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by ChristianMurphy** [comment]
@uPortal-Project/uportal-app-framework-committers I'm invoking lazy consensus on this task.
Barring any objections, I plan on merging this later today.

**Comment by apetro** [comment]
I'd strongly prefer that lazy consensus invocations have a footprint on `uportal-dev@`.

**Comment by ChristianMurphy** [comment]
> I'd prefer that lazy consensus invocations have a footprint on `uportal-dev@`

:unamused:
Lazy consensus is a way of clearing blockers.
I'm not fully onboard with encouraging it.
Ideally people should be reviewing, and leaving explicit :+1: or :-1:.

**Pull request merged**
